#!/usr/bin/env bash
# UFW SETUP

sudo apt-get update
sudo apt-get install ufw -y

sudo ufw default deny incoming
sudo ufw default allow outgoing

sudo ufw allow ssh
sudo ufw allow http
sudo ufw allow https

sudo ufw enable
